spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jdbc01?characterEncoding=utf-8&useSSL=true
  jpa:
    show-sql: true
  rabbitmq:
    username: admin
    password: 123456
    host: localhost
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
